### ISSUE TITLE
`add': undefined method `<=' for nil:NilClass (NoMethodError) 

### ISSUE THREAD

**Issue by PriteshJain** [customink/central_logger#34]
I get following error when I run any scaffold or create model.

I am using rails 3.2.6 and ruby 1.9.3 also central_logger from master branch

``` ruby
/home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/bundler/gems/central_logger-72bba43d1990/lib/central_logger/mongo_logger.rb:46:in `add': undefined method `<=' for nil:NilClass (NoMethodError)
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/buffered_logger.rb:90:in `info'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activerecord-3.2.6/lib/active_record/railtie.rb:80:in `block (2 levels) in <class:Railtie>'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/lazy_load_hooks.rb:42:in `each'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activerecord-3.2.6/lib/active_record/base.rb:721:in `<top (required)>'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/railties-3.2.6/lib/rails/generators/named_base.rb:166:in `pluralize_table_names?'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/railties-3.2.6/lib/rails/generators/named_base.rb:114:in `table_name'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activerecord-3.2.6/lib/rails/generators/active_record/model/model_generator.rb:17:in `create_migration_file'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `each'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:109:in `invoke'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/group.rb:281:in `block in _invoke_for_class_method'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/shell.rb:74:in `with_padding'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/group.rb:270:in `_invoke_for_class_method'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/group.rb:150:in `_invoke_from_option_orm'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `each'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/railties-3.2.6/lib/rails/generators.rb:171:in `invoke'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/railties-3.2.6/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
    from /home/pritesh/.rvm/gems/ruby-1.9.3-p194@rinema/gems/railties-3.2.6/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by stevenkolstad** [comment]
I get this upon trying to install from source on a 3.2.11 app. I'm going to try this on a blank app and see if this is broken functionality due to newer version of Rails, or a localized bug.
